[package]
name = "yaydl"
description = "yet another youtube (and more) down loader"
version = "0.4.0"
authors = ["Cthulhux <git@tuxproject.de>"]
edition = "2018"
license = "CDDL-1.0"
repository = "https://code.rosaelefanten.org/yaydl"
categories = ["command-line-utilities"]
keywords = ["youtube", "vimeo", "voe"]

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
indicatif = "0.15"
inventory = "0.1"
qstring = "0.7"
regex = "1.4"
scraper = "0.12"
serde_json = "1.0"
ureq = { version = "1.5", default_features = false, features = ["native-tls"] }
url = "2.2.0"
urlencoding = "1.1"

[profile.release]
lto = true
